
<script language="javascript" type="text/javascript">
function validateUploadClient()
{
	formControl = document.frmNewClient
	
	
	if(!combocheck(formControl.ddClient,'Client',""))
	{
	return false
	}
	
	file = formControl.fileCsvUpload.value
	if(file == ''){
		alert("Please upload a valid csv file");
		return  false;
	}
}

</script>

<form id="frmNewClient" name="frmNewClient"  action="<?php echo $this->baseUrl(); ?>/client/mapcsv" method="post" onsubmit="return validateUploadClient()" enctype="multipart/form-data"  >
					
<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr> 
		<td height="200" valign="top"  align="center"  >
								
<table class="tableHeading" border="0" cellpadding="5" cellspacing="0" width="100%">
	
	<tr>
		<td width="24%" class="big" align="left" ><strong> New Client Information </strong></td>
		<td class="small" align="center">
		
		<div class="message" id="message" ><?php echo $this->message; ?></div>
		
		</td>
		
	</tr>
	
	
</table>
								
<table border="0" cellpadding="5" cellspacing="0" width="100%">
<tr>
	<td width="21%" align="right" valign="top" class="dvtCellLabel"><span style="color:#FF0000" > * </span> Selected Project Name : </td>
	<td class="dvtCellInfo" align="left"  colspan="3">
	
			<select name="ddClient"  class="ddcontrol" style="width:505px" >
			<option value="" >Select one client</option>
			<?php
				foreach($this->projects as $projects){
			?>
			<option value="<?php echo $projects->project_id; ?>" <?php if($this->projectId ==  $projects->project_id) {echo "selected" ; } ?>  ><?php echo $projects->project_name; ?></option>
			<?php
				}
			?>
		</select>

	
	</td>
</tr>

<tr>
	<td width="21%" align="right" valign="top" class="dvtCellLabel"><span style="color:#FF0000" > * </span>  Select CSV file : </td>
	<td class="dvtCellInfo" align="left"  colspan="3"><input class="textcontrol1"  name="fileCsvUpload" style="width:270px" type="file"  /></td>
</tr>
																		
																		
<tr>
	<td colspan="4" align="center"  class="comment" height="50px"  ><input class="flatinput" type="submit" name="addAccess" value="Next" /> 
	<input class="flatinput" type="reset" name="Submit" value="Reset" /></td>
</tr>

</table>
															    
		</td>
	</tr>
</table>
	
<input type="hidden" name="id" value="<?php echo $this->projectId; ?>" />
						
</form>