<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title><?php echo $this->escape(Zend_Registry::get('title'));  ?></title>
<link href="<?php echo $this->baseUrl(); ?>/public/stylesheet/lc.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl(); ?>/public/style/style.css" rel="stylesheet" type="text/css" />
<script language="javascript" src="<?php echo $this->baseUrl(); ?>/public/jsscripts/validation.js" ></script>

</head>

<?php
    $auth       = Zend_Auth::getInstance();
    $user       = $auth ->getIdentity();
    $fullname   = $user ->name;
	$baseurl    =  $this->baseUrl(); 
        $base_url = Zend_Registry::get('base_url');

?>

<body style="margin:0" >
<table width="100%" border="0" cellpadding="0" cellspacing="10" align="center">
	<tr>
		<td valign="top" background="<?php echo $this->baseUrl(); ?>/public/images/topheaderbg.gif" style="border-bottom:3px solid #5287CF" >
			
			
			
			<table width="100%" border="0" cellpadding="0" cellspacing="0" height="45px">
				<tr>
					<td width="400" align="left" valign="middle"    >
					
					<a href="<?php echo $base_url.'/home'; ?>" > 
					
						<img src="<?php echo $this->baseUrl(); ?>/public/images/small_logo.gif" align="middle" width="45px" height="45px" style="border:0px solid red;vertical-align:middle;margin-left:-10px"  />
						
						
					<span style="font-family:Times New Roman, Times, serif;font-size:20px;font-weight:300;color:#231f20; padding-right:10px;padding-top:11px;border:0px solid green" >
					<?php echo $this->escape(Zend_Registry::get('title'));  ?>					</span>					   </a>					 </td>
					<td  align="right"  valign="middle">
					
					<table width="200" border="0">
                        <tr>
                          <td  align="right" class="time" style="padding-right:0"> 
						  <?php 
						  
						  echo  ($fullname) ? " Welcome :   <b> $fullname </b>":" Welcome : <b>   Guest  </b>  "; 
						  
						  ?>   </td>
                        </tr>
                        <tr>
                          <td  align="center" style="color:#085DBE" >  
						  <?php 
						  	// echo  ($fullname ) ?   " <a href='$baseurl/index/logout' > Logout </a> | <a href='#' > Help </a> ":"<a href=index.php >  Login </a> | <a href='#' >  Help </a>   "; 
						  ?>  </td>
                        </tr>
                      </table></td>
				</tr>
			</table>		
            
            <div id="left-menu"    >
             
                  <ul style="padding-top:0;margin-top:5;margin-bottom:10px;" >
                  <li style="padding:0;margin-left:0;float:left;border:1px solid 000"><a href="<?php echo $this->baseUrl(); ?>/home">Home</a></li>
                  <li><a href="<?php echo $this->baseUrl(); ?>/project">Projects</a></li>
                  <?if ($user->isadmin)
                  {
                  	?><li><a href="<?php echo $this->baseUrl(); ?>/sales">Sales Commission</a></li>
                  		<li><a href="<?php echo $this->baseUrl(); ?>/user">Users</a></li><?
                  }
                  ?>
                  <li><a href="<?php echo $this->baseUrl(); ?>/user/changepass">Change Password</a></li>
                  <?php
                  if($fullname  != ''){ 
                  ?>
                    <li style="float:right;margin-right:0"><a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout </a></li>
                  <?php
                  }
                  ?>
                </ul>
                
                
            </div>	 
            
        
        
        </td>
        
        
	</tr>
	
	<tr>
		
		<td valign="top" align="center"  id="signup" style="padding:10px;text-align:center"  width="800"   height="500" >
			
	 <?php
		echo $this->layout()->content ;
	 ?>	
	 	
&nbsp;	 </td>
	</tr>
	<tr>
		<td  height="50" align="center" bgcolor="#848587" ><p style="padding-left: 10px;color:#FFFFFF"><span style="padding-left: 10px;">Copyright @ Allicance Collection Service Inc All Rights Reserved</span></p></td>
	</tr>
</table>

</body>
</html>

