<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title><?php echo $this->escape(Zend_Registry::get('title'));  ?></title>
<link href="<?php echo $this->baseUrl(); ?>/public/stylesheet/lc.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl(); ?>/public/style/style.css" rel="stylesheet" type="text/css" />
<script language="javascript" src="<?php echo $this->baseUrl(); ?>/public/jsscripts/validation.js" ></script>


</head>

<body >
	 <?php
		echo $this->layout()->content ;
	 ?>	
</body>
</html>

