<link href="<?php echo $this->baseUrl(); ?>/public/stylesheet/style.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl(); ?>/public/jsscripts/jquery/jquery-latest.js" type="text/javascript" ></script>
<script src="<?php echo $this->baseUrl(); ?>/public/jsscripts/jquery/jquery.tablesorter.js" type="text/javascript" ></script>



<script language="javascript">

function confirmDelete(id){

	if(confirm("Are you Sure ? "))
		window.location.href='<?php echo $this->baseUrl();?>/sales/delete/id/' + id
}



function selectAlluser(){
Frm = document.frmUserList
controllength = Frm.selected_id.length

	if(Frm.selectall.checked == true){	
		for(i=0;i<controllength;i++){
		Frm.selected_id[i].checked = true
		}
	}
	else
	{
		for(i=0;i<controllength;i++){
		Frm.selected_id[i].checked = false
		}
	}

}

function selectAtleastOne(){
Frm = document.frmUserList
flag = 0;
controllength = Frm.selected_id.length
		for(i=0;i<controllength;i++){
			if(Frm.selected_id[i].checked == true){
				flag = 1;
				break;
			}
		}
		
	if(flag == 0){
	alert('Please select atleast one teacher!')
	return false
	}
	else if(flag == 1)
	{
				if(confirm('Are you sure?')){
					Frm.submit();
				}

	}
}


function validateSearch()
{
	if(document.search.search_text.value == ''){
		document.search.search_text.focus()
		alert('Please enter search text ! ')
		return false;
	}
	if(document.search.search_option.selectedIndex == 0){
		document.search.search_option.focus()
		alert('Please select option!')
		return false;
	}

}




$(document).ready(function()
{
		$("#myTable").tablesorter(		
				{ headers: { 6: { sorter: false },
							 7: { sorter: false	}
							}
				}
		);
	}
);

</script>

	



<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center"  >
    
<tr>
	<td  height="30px"   valign="middle"  >
								
                                <div class="message" id="message"  style="text-align:center"><?php echo $this->message; ?></div>
                                
                                <div class="breadcrumb" > <a href="<?php echo $this->baseUrl(); ?>/home" > Home </a>  > Sales Commission </div>	
                                	
<table border=0 cellspacing=0 cellpadding=2 width=100% >

<tr>
	<td width="20%"  class="adminsubhead" > Sales Commission    </td>
	<td width=60% align="center" ></td>
	<td width=29% align="right">
    	<a href="<?php echo $this->baseUrl(); ?>/sales/newsales">
    		<img src="<?php echo $this->baseUrl(); ?>/public/images/btnAdd.gif"   border="0"    />
        </a>
	</td>	
</tr>
</table>

									
</td>
</tr>	


<tr> 
<td height="200" valign="top"  align="center"   >
								
<form id="frmUserList" name="frmUserList" action="app/massteachersdelete.php" method="post" onsubmit="return validate()" >
								
<table border=0 cellspacing=1 cellpadding=0 width=100% class="lvtBg">
	<tr><td>
			
            

<table border=0  cellspacing=1 cellpadding=3 width="100%"  id="myTable" class="tablesorter lvt small" >
<thead>
<tr class="bluehead" >

	<th width="25px" > # </th>
	<th width="12%" > Sales Id</th>
	<th width="15%" align="left"   >Commission Percentage</th>
	<th width="35%"    >Notes</th>
	<th align="left" width="109" >Created By</th>
	<th align="left" width="109" >Created Time</th>
	<th align="center" width="75" style="text-align:center;padding-right:5px" >Edit </th>
	<th align="center" width="75" style="text-align:center;padding-right:5px" >Delete</th>
</tr>
</thead>					
	
<tbody>
<?php
$totalRecords =  $this->paginator->getTotalItemCount(); 

$i = 1;
foreach($this->paginator as $record){

if($i%2==1){
	$tr = 'class="eventr"';
} else {
	$tr = 'class="oddtr"';
}

?>

<tr <?php echo $tr ;?> >
	<td ><?php echo $i; ?></td>
	<td><?php echo $record->sales_id;  ?></td>
	<td align="left" ><?php echo $record->sales_comm_percentage;  ?></td>
	<td align="left" ><?php echo $record->notes;  ?></td>
	<td align="left" ><?php echo $record->name;  ?></td>
	<td align="left" ><?php echo $record->created_time;  ?></td>
	<td align="center" ><a class="edit" href="<?php echo $this->baseUrl(); ?>/sales/newsales/id/<?php echo $record->sales_id_prime; ?>" > <img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" /> </a></td>
	<td align="center"  ><a href='#' onclick="javascript:confirmDelete(<?php echo $record->sales_id_prime ; ?>)" ><img src="<?php echo $this->baseUrl(); ?>/public/images/publish_x.png"  /></a></td>
</tr>	
						
<?php
$i++; 
}
	if($totalRecords == 0){
	echo '<tr bgcolor=white class=message ><td colspan=8 align=center>There is no sales commission is active ! </td></tr>';
	}
?>
	</tbody>
 </table>



		</td>
	</tr>
</table>							
		
		
        
        
     
        
        
        
        
		</form>

		</td>
	</tr>
</table>
				
                
                

            		
