<link href="<?php echo $this->baseUrl(); ?>/public/stylesheet/style.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl(); ?>/public/jsscripts/jquery/jquery-latest.js" type="text/javascript" ></script>
<script src="<?php echo $this->baseUrl(); ?>/public/jsscripts/jquery/jquery.tablesorter.js" type="text/javascript" ></script>


<script language="javascript">

function confirmDelete(id){

	if(confirm("Are you Sure ? "))
		window.location.href='<?php echo $this->baseUrl();?>/project/delete/id/' + id
}



function selectAlluser(){
Frm = document.frmUserList
controllength = Frm.selected_id.length

	if(Frm.selectall.checked == true){	
		for(i=0;i<controllength;i++){
		Frm.selected_id[i].checked = true
		}
	}
	else
	{
		for(i=0;i<controllength;i++){
		Frm.selected_id[i].checked = false
		}
	}

}

function selectAtleastOne(){
Frm = document.frmUserList
flag = 0;
controllength = Frm.selected_id.length
		for(i=0;i<controllength;i++){
			if(Frm.selected_id[i].checked == true){
				flag = 1;
				break;
			}
		}
		
	if(flag == 0){
	alert('Please select atleast one teacher!')
	return false
	}
	else if(flag == 1)
	{
				if(confirm('Are you sure?')){
					Frm.submit();
				}

	}
}


function validateSearch()
{
	if(document.search.search_text.value == ''){
		document.search.search_text.focus()
		alert('Please enter search text ! ')
		return false;
	}
	if(document.search.search_option.selectedIndex == 0){
		document.search.search_option.focus()
		alert('Please select option!')
		return false;
	}

}


/*

$(document).ready(function()
{
		
		$("#myTable").tablesorter(		
				{ headers: { 0: { sorter: false },
							 6: { sorter: false	},
							 7: { sorter: false },
							 8: { sorter: false	},
							 9: { sorter: false },
							 10: { sorter: false }
							}
				}
		);
	}
);


*/



function windowOpenClient(){

window.open("<?php echo $this->baseUrl(); ?>/group/clientpopup/id/<?php echo $this->project_id ; ?>","clients","width=820,height=670,resizable=0,scrollbars=1")

}



if (document.all)

	var browser_ie=true

else if (document.layers)

	var browser_nn4=true

else if (document.layers || (!document.all && document.getElementById))

	var browser_nn6=true
	
	
function addOption(lvalue,ltext)	
{
	var optObj = document.createElement('OPTION')
	if (browser_ie) optObj.innerText = ltext;
        else if(browser_nn4 || browser_nn6) optObj.text = ltext;
	else optObj.text = ltext;
	optObj.value = lvalue;
	document.getElementById('parentid').appendChild(optObj);
}


function validate(){

	var totalCount = document.getElementById("parentid").length;
	
	if(totalCount < 2){
		alert("Minimum two clients are needed for a group ! ");
		return false; 	
	}

}


// function to delete activity related contact in calendar
var del_ids = new Array();
function removeActContacts()
{
	var avail_contacts = getObj('parentid');
	// this block is to remove contacts and get deleted contact ids
	if(avail_contacts.options.selectedIndex > -1)
	{
		for(m = 0; m < avail_contacts.options.length; m++)
		{
			if(avail_contacts.options[m].selected == true)
			{
				del_ids.push(avail_contacts.options[m].value);
				avail_contacts.options[m] = null;
				removeActContacts();
			}
		}
	}
	document.frmgroups.deletecntlist.value = del_ids.join(";");
	
	// this block is to get available id list
	var avail_ids = new Array();
	for(n=0; n<avail_contacts.options.length;n++)
	{
		avail_ids.push(avail_contacts.options[n].value);	
	}
	document.frmgroups.contactidlist.value = avail_ids.join(";");
	
}

// function to delete activity related contact in calendar
var del_idsgroup = new Array();
function removeActContactsGroup()
{
	var avail_contactsgroup = getObj('groupparentid');
	// this block is to remove contacts and get deleted contact ids
	if(avail_contactsgroup.options.selectedIndex > -1)
	{
		for(m = 0; m < avail_contactsgroup.options.length; m++)
		{
			if(avail_contactsgroup.options[m].selected == true)
			{
				del_idsgroup.push(avail_contactsgroup.options[m].value);
				avail_contactsgroup.options[m] = null;
				removeActContactsGroup();
			}
		}
	}
	document.frmgroups.deletegrouplist.value = del_idsgroup.join(";");
	
	// this block is to get available id list
	var avail_ids = new Array();
	for(n=0; n<avail_contactsgroup.options.length;n++)
	{
		avail_ids.push(avail_contactsgroup.options[n].value);	
	}
	document.frmgroups.groupidlist.value = avail_ids.join(";");
	
}


function getObj(n,d) {

  var p,i,x; 

  if(!d)

      d=document;

   
   if(n != undefined)
   {
	   if((p=n.indexOf("?"))>0&&parent.frames.length) {

		   d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);

	   }
   }



  if(!(x=d[n])&&d.all)

      x=d.all[n];

 

  for(i=0;!x&&i<d.forms.length;i++)

      x=d.forms[i][n];

 

  for(i=0;!x&&d.layers&&i<d.layers.length;i++)

      x=getObj(n,d.layers[i].document);

 

  if(!x && d.getElementById)

      x=d.getElementById(n);



  return x;

}



</script>

<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center"  >
    
<tr>
	<td  height="30px" valign="middle"  >

<div class="message" id="message"  style="text-align:center"><?php echo $this->message; ?></div>
                                
                                
<div class="breadcrumb" > <a href="<?php echo $this->baseUrl(); ?>/home" > Home </a>  >
<a href="<?php echo $this->baseUrl(); ?>/project" >  Projects  </a>  >
<a href="<?php echo $this->baseUrl(); ?>/project/projecthome/id/<?php echo $this->project_id ; ?>" > <?php echo $this->project_name ; ?> </a>
>  Groups </div>                                
                                
                                
<table border=0 cellspacing=0 cellpadding=2 width=100% >

<tr>
	<td width="20%"  class="adminsubhead" > 

    Groups
    
    </td>
	<td width=60% align="center" ></td>
	<td width=29% align="right">

    </td>	
</tr>
</table>
									
</td>
</tr>	

<tr>
<td height="200" valign="top"  align="center"   >
								
<form id="frmgroups" name="frmgroups" action="<?php echo $this->baseUrl(); ?>/group/save" method="post" onsubmit="return validate()" >
								
<table border="0" cellspacing=1 cellpadding=0 width=100% class="lvtBg">
	<tr><td valign="top">

			 

<table class="tableHeading topheading" border="0" cellpadding="5" cellspacing="0" width="100%">
	<tbody>
		<tr>
			<td class="big" align="left" ><strong> New Group </strong></td>
		</tr>
	</tbody>
</table>


								
<table border="0" cellpadding="5" cellspacing="0" width="100%">
	<tr>
		<td width="21%" align="right" valign="top" class="dvtCellLabel"><span style="color:#FF0000" > * </span> Assigned Clients : </td>
		<td class="dvtCellInfo" align="left"  colspan="3">
        
        <input id="contactidlist" type="hidden" value="" name="contactidlist"></input>
        <input id="deletecntlist" type="hidden" name="deletecntlist"></input>
		
        <select class="controltext"  name="contactlist"  id="parentid" multiple="multiple" style="width:70%;height:200px"   >

        </select>
        
            <br />

<input class="flatinput controltext" type="button" onclick="javascript:windowOpenClient()" style="height:20px;padding:0;margin-top:5px" value="Select Clients" name="Submit"></input>
<input class="flatinput controltext" type="button" onclick="removeActContacts()" style="height:20px;padding:0" value="Clear" name="Submit"></input>


		
		</td>
	</tr>
	
	<tr>
		<td colspan="4" align="center"  class="comment" height="50px"  >
		
			<input class="flatinput" type="submit" name="save" value="Save" /> 
			<input class="flatinput" type="reset" name="reset" value="Reset" />
        	<input id="id" type="hidden" name="id" value="<?php echo $this->project_id; ?>" ></input>
		
		</td>
	</tr>
</table>

		       


		</td>
	
    
<td width="50%"  valign="top" style="padding-top:10px;padding-left:10px" >
    
    

<table border=0  cellspacing=1 cellpadding=5 width="100%"   class="tablesorter lvt small" >
<thead>
<tr class="bluehead" >

	<th width="20px" style="padding-right:0px" > # </th>
	<th width="200" > Client Group</th>
	<th align="center" width="220" style="text-align:left;padding-right:5px" >Client Name In Group</th>
	<th align="center" width="67" style="text-align:center;padding-right:5px" >Ungroup</th>
</tr>
</thead>					
	
<tbody>

<?php

$totalRecords =  $this->paginator->getTotalItemCount(); 

$i = 1;

foreach($this->paginator as $record){

if($i%2==1){
	$tr = 'class="eventr"';
} else {
	$tr = 'class="oddtr"';
}

?>

<tr <?php echo $tr ;?> >
	<td ><?php echo $i; ?></td>
	<td><?php echo $record->group_name ; ?></td>
	<td align="left"  ><?php echo $record->group_items ; ?></td>
	<td align="center"  valign="middle"  ><a href='#' onclick="javascript:confirmDelete(<?php echo $record->sales_id_prime ; ?>)" ><img   src="<?php echo $this->baseUrl(); ?>/public/images/publish_x.png"   /></a></td>
</tr>	
						
<?php
$i++; 
}
	if($totalRecords == 0){
	echo '<tr bgcolor=white class=message ><td colspan=8 align=center>There is no group is active ! </td></tr>';
	}
?>
	</tbody>
 </table>



    
    	
    
    </td>
    
    </tr>
    
</table>							
		
		
		</form>

		</td>
	</tr>
</table>
						
