
<script language="javascript" type="text/javascript">
function validateProject()
{

	formControl = document.frmNewUser
	
	if(!emptycheck(formControl.username,'User name',""))
	{
		return false
	}
	if(!emptycheck(formControl.name,'Name',""))
	{
		return false
	}
	if(!emptycheck(formControl.phone,'Phone',""))
	{
		return false
	}
	if(!emptycheck(formControl.email,'E-mail',""))
	{
		return false
	}
	if(!emptycheck(formControl.mobile,'Mobile',""))
	{
		return false
	}				
	if((formControl.password.value != '') 
		&& !passwordcheck(formControl.password))
	{
	return false
	}
}

</script>

<form id="frmNewUser" name="frmNewUser" action="<?php echo $this->baseUrl(); ?>/user/save" method="post" onsubmit="return validateProject()" >
					
<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
<tr>
	<td height="200" valign="top"  align="center" >

<div class="breadcrumb" > <a href="<?php echo $this->baseUrl(); ?>/home" > Home </a>  >
<a href="<?php echo $this->baseUrl(); ?>/user" >  Users  </a>  >
User Info </div>


<table class="tableHeading topheading" border="0" cellpadding="5" cellspacing="0" width="100%">
	<tbody>
		<tr>
			<td class="big" align="left" ><strong> User Info </strong></td>
			<td class="small" align="right"></td>
		</tr>
	</tbody>
</table>



<table border="0" cellpadding="5" cellspacing="0" width="100%">
	<tr>
		<td class="dvtCellLabel" align="right" width="25%"><span class="redfont"> * </span>  User name  </td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="text" value="<?=$this->data->username; ?>" name="username" />
		</td>
		<td class="dvtCellLabel label" align="right" width="25%"><span style="color:#FF0000"> * </span>  Role</td>
		<td class="dvtCellInfo" align="left" width="25%">
			<select  class="ddcontrol"  name="isadmin">
				<option value="0"<?=(!$this->data->isadmin  ? ' selected="selected"' : '')?>>Manager</option>
				<option value="1"<?=($this->data->isadmin ? ' selected="selected"' : '')?>>Administrator</option>
			</select>		
		</td>    
	</tr>
	<tr>
		<td class="dvtCellLabel" align="right" width="25%"><span class="redfont"> * </span> Name  </td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="text" value="<?=$this->data->name; ?>" name="name" />
		</td>
		<td class="dvtCellLabel label" align="right" width="25%"><span style="color:#FF0000"> * </span>  E-mail</td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="text" value="<?=$this->data->email; ?>" name="email" />		
		</td>    
	</tr>	
	<tr>
		<td class="dvtCellLabel" align="right" width="25%"><span class="redfont"> * </span> Mobile  </td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="text" value="<?=$this->data->mobile; ?>" name="mobile" />
		</td>
		<td class="dvtCellLabel label" align="right" width="25%"><span style="color:#FF0000"> * </span>  Phone</td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="text" value="<?=$this->data->phone; ?>" name="phone" />		
		</td>    
	</tr>		
	<tr>
		<td class="dvtCellLabel" align="right" width="25%">Created Time  </td>
		<td class="dvtCellInfo" align="left" width="25%">
			<?=$this->data->date_of_creation ? date("d M Y, H : i A",$this->escape($this->data->date_of_creation)) : '';?>
		</td>
		<td class="dvtCellLabel label" align="right" width="25%">Last Login Time</td>
		<td class="dvtCellInfo" align="left" width="25%">
			<?=$this->data->lastlogin ? date("d M Y, H : i A",$this->escape($this->data->lastlogin)) : '';?>		
		</td>    
	</tr>	
	<tr>
		<td class="dvtCellLabel" align="right" width="25%">Password  </td>
		<td class="dvtCellInfo" align="left" width="25%">
			<input class="textcontrol1" type="password" value="" name="password" />
		</td>
		<td class="dvtCellLabel label" align="right" width="25%"></td>
		<td class="dvtCellInfo" align="left" width="25%">
				
		</td>    
	</tr>		
	<tr>
		<td colspan="4" align="center"  class="comment" height="50px"  >
		
			<input class="flatinput" type="submit" name="save" value="Save" /> 
			<input class="flatinput" type="reset" name="reset" value="Reset" />
			<input class="flatinput" type="hidden" name="id" value="<?=$this->data->user_id ?>" />
		
		</td>
	</tr>
</table>


	</td>
</tr>
</table>
						
</form>