<script src="<?php echo $this->baseUrl(); ?>/public/includes/charts/FusionCharts.js" ></script>

<form  name="frmsignup" id="frmsignup" action="index.php?page=adduser" method="post"    onsubmit="return validateSignup()" >
					
<table width="100%" border="0" cellpadding="0"   cellspacing="0" align="center">
	<tr>
		<td  valign="top"  align="center"  >
		
<table class="tableHeading" border="0" cellpadding="5" cellspacing="0" width="100%">
	<tbody><tr>
		<td align="left" class="big"><strong>  1. Overall Dashboard</strong></td>
		<td class="small" align="right">&nbsp;</td>	
	</tr></tbody>
</table>

<table border="0" cellpadding="5"  class="tableHeading" cellspacing="0" width="100%" style="margin-bottom:20px;border-top:0">
	<tbody><tr>
		<td align="center">	
		
<div id="chartdiv" align="center">The chart will appear within this DIV</div>

     <script type="text/javascript">
       var myChart = new FusionCharts("<?php echo $this->baseUrl(); ?>/public/includes/charts/FCF_MSColumn3D.swf", "myChartId", "1000", "350");
       myChart.setDataURL("<?php echo $this->baseUrl(); ?>/public/includes/charts/multi.xml");
       myChart.render("chartdiv");
     </script>
        
        </td>
	</tr></tbody>
</table>	
                          
<table class="tableHeading" border="0" cellpadding="5" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="big" align="left" ><strong> 2. Logged In User Details </strong></td>
		<td class="small" align="right">&nbsp;</td>
	</tr></tbody>
</table>

<table border="0" cellpadding="5" cellspacing="0" width="100%">
<tbody>

<tr>
	<td class="dvtCellLabel" align="right" width="25%">Name</td>
	<td class="dvtCellInfo" align="left" width="25%"><?php echo $this->escape($this->user->name); ?></td>
	<td class="dvtCellLabel" align="right" width="25%">User Name</td>
	<td class="dvtCellInfo" align="left" width="25%"><?php echo $this->escape($this->user->username); ?></td>    
</tr>

<tr>
	<td class="dvtCellLabel" align="right" width="25%">Password</td>
	<td class="dvtCellInfo" align="left" width="25%"><a href="<?php echo $this->baseUrl(); ?>/user/changepass" >CHANGE PASSWORD</a></td>	
	<td class="dvtCellLabel" align="right" width="25%">Email</td>
	<td class="dvtCellInfo"  align="left" width="25%"><?php echo $this->escape($this->user->email); ?> </td>
</tr>

<tr>
	<td class="dvtCellLabel" align="right" width="25%">Mobile</td>
	<td class="dvtCellInfo" align="left" width="25%"><?php echo $this->escape($this->user->mobile); ?></td>
	<td class="dvtCellLabel" align="right" width="25%">Is Admin ? </td>
	<td class="dvtCellInfo" id="mouseArea_First Name"  align="left" width="25%"><?php echo ($this->escape($this->user->isadmin)?"Yes":"No" ); ?></td>
</tr>
																		  
<tr>
	<td class="dvtCellLabel" align="right" width="25%">Phone</td>
	<td class="dvtCellInfo" id="mouseArea_Currency"  align="left" width="25%"><?php echo $this->escape($this->user->phone); ?>&nbsp;
	<td class="dvtCellLabel" align="right" width="25%"> &nbsp;Last Login Time </td>
	<td class="dvtCellInfo" id="mouseArea_Last Name"  align="left" width="25%"><?php echo date("d M Y , H : i A",$this->escape($this->user->lastlogin) ) ;  ?></td>
</tr>

</tbody></table>
                                                                        
		</td>
	</tr>
</table>
						
</form>